### ISSUE TITLE
java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by pcbeard** [jython234/MagicClient#1]
When I try to connect to a 0.10.4 multiplayer game with MCPE, flat world, I get an exception:

```
at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
at java.nio.ByteBuffer.get(ByteBuffer.java:715)
at net.beaconpe.magicclient.network.encap.RakNetInternalPacket.fromCustomPacket(RakNetInternalPacket.java:88)
at net.beaconpe.magicclient.network.encap.RakNetCustomPacket.decode(RakNetCustomPacket.java:43)
at net.beaconpe.magicclient.network.PacketHandler.handleCustomPacket(PacketHandler.java:240)
at net.beaconpe.magicclient.network.PacketHandler.handlePacket(PacketHandler.java:227)
at net.beaconpe.magicclient.network.PacketHandler.run(PacketHandler.java:192)
```

This is while decoding a packet of type 0x84, length = 317.

**Comment by alejzeis** [comment]
This is PocketMine or vanilla?

On Sunday, February 15, 2015, pcbeard notifications@github.com wrote:

> When I try to connect to a 0.10.4 multiplayer game with MCPE, flat world,
> I get an exception:
> 
> at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
> at java.nio.ByteBuffer.get(ByteBuffer.java:715)
> at net.beaconpe.magicclient.network.encap.RakNetInternalPacket.fromCustomPacket(RakNetInternalPacket.java:88)
> at net.beaconpe.magicclient.network.encap.RakNetCustomPacket.decode(RakNetCustomPacket.java:43)
> at net.beaconpe.magicclient.network.PacketHandler.handleCustomPacket(PacketHandler.java:240)
> at net.beaconpe.magicclient.network.PacketHandler.handlePacket(PacketHandler.java:227)
> at net.beaconpe.magicclient.network.PacketHandler.run(PacketHandler.java:192)
> 
> This is while decoding a packet of type 0x84, length = 317.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/MagicClient/issues/1.

##

**Comment by pcbeard** [comment]
Connecting to vanilla MCPE. I think part of the problem is this code:

```
public static RakNetInternalPacket fromCustomPacket(ByteBuffer bb){
    byte flag = bb.get();
    p.reliability = (byte) (flag >> 5);
```

If the value of flag is 0x80, this shift results in a negative value for reliability because Java's byte type is signed (ick). If I change it to:

```
    p.reliability = (byte) ((flag >> 5) & 0x7);
```

then the values are all correct. However, I still see some problems decoding some encapsulated packets. I've added more logging, and this is what I'm seeing:

```
public static RakNetInternalPacket fromCustomPacket(ByteBuffer bb){
    RakNetInternalPacket p = new RakNetInternalPacket();
    byte flag = bb.get();
    p.reliability = (byte) ((flag >> 5) & 0x7);
    p.hasSplit = (flag & 0x10) == 0x10;
    System.out.println("fromCustomPacket: flag = " + String.format("0x%02x ", flag) + ", reliability = " + p.reliability + ", hasSplit = " + p.hasSplit);
    int bits = bb.getShort() & 0x0000FFFF;
    if ((bits & 0x7) != 0) System.out.println("non byte-aligned value of bits: " + bits);
```

RakNetCustomPacket.decode(): seqNum=4, Length is: 302
fromCustomPacket: flag = 0x60 , reliability = 3, hasSplit = false
fromCustomPacket: length = 41, remaining = 288
fromCustomPacket: flag = 0x40 , reliability = 2, hasSplit = false
fromCustomPacket: length = 10, remaining = 241
fromCustomPacket: flag = 0x60 , reliability = 3, hasSplit = false
non byte-aligned value of bits: 41
fromCustomPacket: length = 5, remaining = 221
fromCustomPacket: flag = 0x80 , reliability = 4, hasSplit = false
fromCustomPacket: length = 2048, remaining = 206
Exception in thread "PacketHandler" java.nio.BufferUnderflowException
    at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
    at java.nio.ByteBuffer.get(ByteBuffer.java:715)
    at net.beaconpe.magicclient.network.encap.RakNetInternalPacket.fromCustomPacket(RakNetInternalPacket.java:91)
    at net.beaconpe.magicclient.network.encap.RakNetCustomPacket.decode(RakNetCustomPacket.java:43)
    at net.beaconpe.magicclient.network.PacketHandler.handleCustomPacket(PacketHandler.java:257)
    at net.beaconpe.magicclient.network.PacketHandler.handlePacket(PacketHandler.java:230)
    at net.beaconpe.magicclient.network.PacketHandler.run(PacketHandler.java:195)

**Comment by pcbeard** [comment]
Moreover, looking at PocketMine's implementation we see:

```
        $length = (int) ceil(Binary::readShort(substr($binary, 1, 2)) / 8);
```

So, if the value of bits is not an exact multiple of 8, length will be rounded up to the next byte value.

**Comment by alejzeis** [comment]
Ahh I see.

On Sunday, February 15, 2015, pcbeard notifications@github.com wrote:

> Moreover, looking at PocketMine's implementation we see:
> 
> ```
>     $length = (int) ceil(Binary::readShort(substr($binary, 1, 2)) / 8);
> ```
> 
> So, if the value of bits is not an exact multiple of 8, length will be
> rounded up to the next byte value.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/MagicClient/issues/1#issuecomment-74443301.

##

**Comment by alejzeis** [comment]
Strangely I never had this problem. I guess it's because I always tested
against pocketmine.

On Sunday, February 15, 2015, Alejandro Zeise atzeise@gmail.com wrote:

> Ahh I see.
> 
> On Sunday, February 15, 2015, pcbeard <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Moreover, looking at PocketMine's implementation we see:
> > 
> > ```
> >     $length = (int) ceil(Binary::readShort(substr($binary, 1, 2)) / 8);
> > ```
> > 
> > So, if the value of bits is not an exact multiple of 8, length will be
> > rounded up to the next byte value.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jython234/MagicClient/issues/1#issuecomment-74443301
> > .
> 
> ## 

##

**Comment by pcbeard** [comment]
I'd really like to get this working with vanilla if possible.

**Comment by alejzeis** [comment]
I see, my plans for it included a javascript api with events and all. But I
didn't think many people would use it with vanilla.

On Sunday, February 15, 2015, pcbeard notifications@github.com wrote:

> I'd really like to get this working with vanilla if possible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/MagicClient/issues/1#issuecomment-74443676.

##

**Comment by pcbeard** [comment]
I'm mainly seeing this underflow when getting chunk data. A RakNetCustomPacket receives 1447 bytes of data to decode. The RakNetInternalPacket reads a short value() (unsigned) of 39656 bits, or 4957 bytes, but the packet only contains 1433 bytes. It's immediately followed by another packet that says it contains 4525 bytes, but only 1433 are present. I'm pretty sure the MTU values start at 1447, so I'm unsure how chunks are sent. I was assuming that's what split packets were for. Confusing!

**Comment by alejzeis** [comment]
@pcbeard I think I know what's wrong. Since chunk packets are sent split, my decoding method reads the short value too late or too early and gets the wrong value. Still not sure.

**Comment by alejzeis** [comment]
Wait the flag is 0x80? I've never seen that one before...

**Comment by pcbeard** [comment]
That may have been caused by mis-reading a split packet as you said.

**Comment by alejzeis** [comment]
Strange, even the split packet format has the length come first.

On Monday, February 23, 2015, pcbeard notifications@github.com wrote:

> That may have been caused by mis-reading a split packet as you said.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jython234/MagicClient/issues/1#issuecomment-75589083.

##
